version: 2
jobs:
  terraform-plan:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Plan
          command: echo Plan
  terraform-apply:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Apply
          command: echo Apply

workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform-plan:
          filters:
            branches:
              ignore: master
      - terraform-apply:
          filters:
            branches:
              only: master  
