version: 2
jobs:
  terraform_plan:
    docker:
      - image: debian:stretch
    branches:
      ignore:
        - master
    steps:
      - checkout
      - run:
          name: Plan
          command: echo Plan
  terraform_apply:
    docker:
      - image: debian:stretch
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Apply
          command: echo Apply
