version: 2
jobs:
  terraform_plan:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Plan
          command: echo Plan
  terraform_apply:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Apply
          command: echo Apply

workflows:
  version: 2
  deploy:
    jobs:
      - terraform_plan:
          filters:
            branches:
              ignore: master
      - terraform_apply:
          filters:
            branches:
              only: master  
